### ISSUE TITLE
Which dockerhub to follow for the latest releases?

### ISSUE THREAD

**Issue by HJJ256** [eoranged/rq-dashboard#484]
Hi, @eoranged and @cjlapao I see 2 docker hub repos for the rq-dashboard images, with the latest one being @cjlapao's repo. 

https://hub.docker.com/r/eoranged/rq-dashboard
https://hub.docker.com/r/cjlapao/rq-dashboard

Is there a definite place where the newest version will always be available (without building from Dockerfile)? Would it always be https://hub.docker.com/r/cjlapao/rq-dashboard ?

Thanks in advance

**Comment by cjlapao** [comment]
@HJJ256 

Yes, the official one that the workflow is publishing to is the https://hub.docker.com/r/cjlapao/rq-dashboard
This might change in the future once Parallels has it's own docker registry but we will be notifying users of it

Thanks
