### ISSUE TITLE
Metadata and Dependency information in the job view

### ISSUE THREAD

**Issue by dopc** [eoranged/rq-dashboard#489]
Hi, thanks for this great project.

I kindly ask to have meta and dependency (jobs which the viewed job depends on) info in the job view.

That would be super useful if you could add them.
Also, I can come with a PR, if it is not difficult for me. 
Please don't hesitate to guide me on how to do that :)

Best.

**Comment by dopc** [comment]
Here is my PR, #490 .

**Comment by cjlapao** [comment]
@dopc Thanks for the pull request, this is now merged and will be released in a bit to master
